In [64]:
import os
import json
import pandas as pd
import h5py
import numpy as np
#import geopandas as gpd

In [31]:
# test labels
#labels = '/mnt/lustre02/work/ka1176/shared_data/2021-ai4food/raw_data/ref_fusion_competition_south_africa_test_labels/ref_fusion_competition_south_africa_test_labels_34S_20E_259N/labels.geojson'
#south_africa_te_labels=gpd.read_file(labels)

In [181]:
train_data = h5py.File('/work/ka1176/shared_data/2021-ai4food/dev_data/planet/default/train_data.h5', 'r')
test_data = h5py.File('/work/ka1176/shared_data/2021-ai4food/dev_data/planet/default/test_data.h5', 'r')

In [182]:
file_sub = '../../ai4food/submission.json'
file_val = '../../ai4food/validation.json'
# Opening JSON file
f = open(file_sub,)
# returns JSON object as
# a dictionary
data_sub = json.load(f)
f = open(file_val,)
data_val = json.load(f)

In [183]:
train_data.keys()

<KeysViewHDF5 ['fid', 'image_stack', 'label', 'mask']>

In [184]:
test_data.keys()

<KeysViewHDF5 ['fid', 'image_stack', 'label', 'mask']>

In [185]:
data_val.keys()

dict_keys(['fid', 'crop_id', 'crop_name', 'crop_probs'])

In [186]:
data_sub.keys()

dict_keys(['fid', 'crop_id', 'crop_name', 'crop_probs'])

In [187]:
np.unique(train_data['label'][:])

array([0, 1, 2, 3, 4])

In [188]:
np.unique(list(data_val['crop_id'].values()))

array([1, 2, 3, 4, 5])

In [189]:
np.unique(list(data_sub['crop_id'].values()))

array([1, 2, 5])

In [197]:
len(data_sub['crop_id'])

2407

In [190]:
len(data_val['fid'])

829

In [191]:
len(data_sub['fid'])

2407

In [192]:
# validation data length
len(train_data['label'][:])-int(len(train_data['label'][:])*0.8)

829

In [193]:
len(test_data['fid'][:])

2407

In [194]:
test_data['fid'][:]

array([185471, 185489, 185490, ..., 272429, 272640, 272740])

In [195]:
ct = 0
for i,item in enumerate(data_sub['fid'].items()):
    if item[1][0] not in test_data['fid']:
        ct+=1
        print(i, test_data['fid'][i])
print(ct)

0


In [196]:
for i in range(len(test_data['fid'][:])):
    if test_data['fid'][i] not in data_sub['fid'].values():
        print(i, test_data['fid'][i])

In [ ]:
#assert len(data) == len(south_africa_te_labels), "WARNING: The size of the predictions is not equal to number of test fields. " \
#"Number of test fields: {}, Number of predictions: {}".format(len(output_frame),len(south_africa_te_labels))